Adding additional context for deblur tables
biocore/cmi-workshops pull request #37
Opened 2018-07-26 16:15 UTC by adswafford

2018-08-27 17:28 UTC, tkosciolek requested changes

2018-08-27 17:28 UTC, tkosciol commented on docs/qiita-16S-analysis.rst
> +Qiita employs Deblur v1.0.4 on trimmed sequences (UC San Diego studies are typically processed with 90, 100, and 150 nt) with no minimum read threshold count, followed by insertion into the latest (A
should read:
```
Qiita employs Deblur v1.0.4 on trimmed sequences (UC San Diego studies are typically processed with 90, 100, and 150 nt) with no minimum read threshold count, followed by insertion into the latest (Aug 2013) 99% OTU tree from GreenGenes using SEPP as part of the QIIME2 `q2-fragment-insertion plugin<https://github.com/biocore/q2-fragment-insertion>`__.
```

2018-08-27 17:28 UTC, tkosciol commented on docs/qiita-16S-analysis.rst
> +In addition, by deblurred sequences in Qiita use a reduced threshold for sequence abundance across all samples of 1 read rather than the 10 read threshold default in deblur. The single read threshold
Filter Table command in the last sentence should include a link

2018-08-27 19:47 UTC, stephanieorch commented
@tkosciol hyperlink is fixed and I believe I set up the anchor the correct way so everything should be working fine now

2018-08-28 17:52 UTC, tkosciol commented
@stephanieorch in preview the anchor still does not look correct

2018-08-28 17:54 UTC, stephanieorch commented
This is how I did it in the qiita help documentation. It doesn't look correct until it's pushed through. So it should work correctly.

2018-08-28 18:01 UTC, merged